title: "An attempt at a tutorial utilising AWS for Scalable Image-Based Transcriptomic Data Analysis"
theme: minima

markdown: kramdown

repository: "jeffreytjs/zb4171-AWS-batch-tutorial"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
